name: 'atlas-sync-action'
description: 'Sync your migration directory to Atlas Cloud'
branding:
  icon: database
author: 'Ariga'
inputs:
  dir:
    description: 'The path to the directory containing your migrations.'
    required: true
  name:
    description: 'The name of the migration directory in Atlas Cloud.'
    required: true
  tag:
    description: 'The tag of the specific version of the migration directory.'
    required: false
  dev-url:
    description: 'The URL of the dev database to connect to.'
    required: true
  cloud-token:
    description: 'The Atlas Cloud token to use for authentication. Must be passed as a secret.'
    required: true
outputs:
  url:
    description: 'URL of the new directory/tag'

runs:
  using: 'docker'
  image: 'docker://arigaio/atlas-sync-action:latest'
