name: 'atlas-sync-action'
description: 'Sync your migration directory to Atlas Cloud'
branding:
  icon: database
author: 'Ariga'
inputs:
  dir:
    description: 'select migration directory relative to working directory'
    required: true
  cloud-token:
    description: 'Token for using Atlas Cloud (should be passed as a secret).'
    required: true
  driver:
    description: 'Driver for the target database: mysql, postgres, sqlite'
    required: true
runs:
  using: 'docker'
  image: 'docker://arigaio/atlas-sync-action:latest'
